config/routes.rb
Rails.application.routes.draw do
  get 'bookings/create'
  devise_for :users
  root to: 'pages#home'

  get '/profile', to: 'pages#profile', as: :profile
  post '/profile', to: 'pages#image_upload', as: :profile_upload

  resources :dogs do
    resources :bookings, only: [:create]
  end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :dog_id, presence: true
  validates :user_id, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates :breed, presence: true
  validates :cuddly, presence: true
  validates :energetic, presence: true
  validates :obedient, presence: true
  validates :couchpotato, presence: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :dogs
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:fullname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:fullname, :email, :password, :current_password, :is_female, :date_of_birth) }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    year = params[:booking]["start_date(1i)"].to_i
    month = params[:booking]["start_date(2i)"].to_i
    day = params[:booking]["start_date(3i)"].to_i
    start_date = Date.new(year, month, day)

    year = params[:booking]["end_date(1i)"].to_i
    month = params[:booking]["end_date(2i)"].to_i
    day = params[:booking]["end_date(3i)"].to_i
    end_date = Date.new(year, month, day)

    @booking = Booking.new(start_date: start_date, end_date: end_date, user_id: current_user.id, dog_id: params[:dog_id])
    @booking.save!
    redirect_to profile_path, notice: 'High 5 with your dog soon! Woof!!'
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to profile_path, notice: 'Your booking has been deleted! Woof!!'
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    @booking = Booking.new
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to profile_path, notice: 'Your new dog profile has been created! Woof!'
    else
      render :new
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to profile_path, notice: 'Dog was successfully removed.'
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :photo, :breed, :postcode, :age, :sex, :description, :cuddly, :energetic, :obedient, :couchpotato, :price, :photo_cache)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def profile
    @user = current_user
  end

  def image_upload
    current_user.photo = user_params[:photo]
    current_user.save!
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_form.html.erb
<div class="row">
  <div class="dog-form col-6">
    <%= simple_form_for [@dog] do |f| %>
    <%= f.input :name %>
    <%= f.input :breed %>
    <%= f.input :description %>
    <%= f.input :sex, :label => 'Female or Male?' %>
    <%= f.input :age, priority: [ "Puppy" ], collection: ["Puppy", "Teen", "Adult", "Senior"]%>
  </div>


  <div class="dog-form-2 col-6">
    <%= f.input :cuddly, priority: [ 5 ], collection: [1, 2, 3, 4 ,5] %>
    <%= f.input :energetic, priority: [ 5 ], collection: [1, 2, 3, 4 ,5] %>
    <%= f.input :obedient, priority: [ 5 ], collection: [1, 2, 3, 4 ,5] %>
    <%= f.input :couchpotato, priority: [ 5 ], collection: [1, 2, 3, 4 ,5] %>
    <%= f.input :price, :hint => "Per day, in CAD."%>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="heading">
  <h1> Dogs Ready For<br>Hangout </h1>
</div>

<div class="scroll-left">
      <p class="scroll-text">Black Friday Special Promotion! Ends TODAY at 7 p.m.! All dogs 20% off!</p>
</div>

<div class="card-container">
  <% @dogs.each do |dog| %>
  <div class="card-trip">
    <%= cl_image_tag dog.photo %>
    <div class="card-trip-infos">
      <div>

        <div class= 'd-flex position-relative'>
        <h2 class= 'woof-hover'><%= link_to dog.name, dog_path(dog) %></h2>
         <%= image_tag "woof.png", alt: "woof", class:'woof' %>
        </div>

        <span><%= dog.breed %>  <%= dog.sex %>  <%= dog.age %></span>
        <div class="dog-traits">
          <div class="dog-characteristics">
            <p class="mr-4">Cuddly&nbsp;<% dog.cuddly.to_i.times do  %>
              <i class="fas fa-paw mr-1"></i>
            <% end %>
            </p>
            <p>Energetic&nbsp;<% dog.energetic.to_i.times do %>
              <i class="fas fa-paw mr-1"></i>
              <% end %>
            </p>
          </div>
          <div class="dog-characteristics">
            <p>Obedient&nbsp; <% dog.obedient.to_i.times do  %>
              <i class="fas fa-paw mr-1"></i>
            <% end %>
            </p>
            <p>Couchpotato&nbsp; <% dog.couchpotato.to_i.times do %>
              <i class="fas fa-paw mr-1"></i>
            <% end %>
            </p>
          </div>
        </div>
      </div>
      <p class="dog-price">$<%= dog.price %></p>
    </div>
  </div>
  <% end %>


</div>
<%#= link_to "Add your  dog", new_new_path %>

app/views/dogs/new.html.erb
<div class=container>
  <h1>New Dog<br>In<br>Town</h1>
</div>

<div class='d-flex justify-content-center pt-3'>
   <div class='liftadog' src=""></div>
</div>

<div class="new-dog-form"><%= render 'form' %></div>

app/views/dogs/show.html.erb
<div class="show-container">
  <div class="show-header">
    <div class="card-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @dog.photo, width: 400, crop: :fill %>')">
    <h1 id="dog-name"><%= @dog.name %></h1>
    </div>
  </div>



    <div>
      <p id="price">
        <span>$<%= @dog.price %>/per day</span>
       </p>
    </div>



    <br>
    <div class="row dog-intro">
      <div class="col-7">
      <p>I am a <%= @dog.breed %> breed.</p>

      <p>I am a <%= @dog.sex %>, <%= @dog.age %> dog.</p>
      </div>
    </div>


    <div>
      <div class="description">
        <p>A little about me</p>
      </div>
      <div class="description-content">
      <p><%= @dog.description %></p>
      </div>
    </div>






  <div class='d-flex justify-content-between'>
    <div class="card-info">
      <div class="left">
        <p><strong>Cuddly&nbsp;&nbsp;</strong><% @dog.cuddly.times do %><i class="fas fa-paw mr-1"></i>
        <% end %></p>

        <p><strong>Obedient&nbsp;&nbsp;</strong><% @dog.obedient.times do %><i class="fas fa-paw mr-1"></i>
        <% end %></p>
      </div>


      <div class="right">
        <p><strong>Energetic&nbsp;&nbsp;</strong><% @dog.energetic.times do %><i class="fas fa-paw mr-2"></i><% end %></p>
        <p><strong>Couchpotato&nbsp;&nbsp;</strong><% @dog.couchpotato.times do %><i class="fas fa-paw mr-2"></i><% end %></p>
      </div>
    </div>
  </div>

  <div class = container>
    <%= simple_form_for [@dog, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <br>

    <div class='text-center' id='show-hover-btn'>
    <%= f.submit "Book Me", class: "woof-hover btn btn-primary" %>
      <%= image_tag "woof.png", alt: "woof", class:'woof' %>
    </div><% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DoggyBeWithMe</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'Logo_Dog_fav.png' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>


  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class='landing-page-h1'>Cuddle<br>Me</h1>

<div class='d-flex justify-content-center pt-3'>
   <div class='high5dog' src=""></div>
</div>


<h2 class='landing-page-subtitle'>
  <span id="banner-typed-text"></span>
</h2>

<div class='cursor-pointer'>
<%= link_to image_tag('paw.png', class: 'paw'), dogs_path %>
</div>

app/views/pages/profile.html.erb
<div class="">
<div class="ml-5 mt-5">
  <h5 id="fullname"> <%= @user.fullname %> </h2>
  <h5 id="welcome">Welcome!</h1>
</div>

<div class="row mt-5 pt-5">


  <div class="col-6">

    <h2 class="booking">My Dogs</h2>
    <% current_user.dogs.each do |dog| %>
     <div>
      <div class="d-flex justify-content-center">
        <div class="card-show-photo" id="my-dog-avatar" style="background-image: url('<%= cl_image_path dog.photo%>')">
        </div>
      </div>
      <h3 class="text-center"><%= link_to dog.name, dog_path(dog) %></h3>
      <%= link_to 'Remove', dog, method: :delete, data: { confirm: 'Are you sure you want to remove your dog? Woof!' }, class: "btn btn-primary remove-btn" %>
    </div>
    <% end%>
  </div>

  <div class="col-6">
    <h2 class="booking">Recent Hangouts</h2>

    <% current_user.bookings.each do |booking| %>
    <div>

    <% dog = Dog.find(booking.dog_id) %>

    <div class="d-flex row align-items-center">
      <div class="card-show-photo" id="dog-avatar" style="background-image: url('<%= cl_image_path dog.photo %>')">
      </div>
      <div class="ml-5 mt-5">
        <h3><%= link_to dog.name, dog_path(dog) %></h3>
        <p>Owner Contact E-mail :&nbsp;<%= dog.user.email %></p>
        <p>Booking Dates :&nbsp;<%= booking.start_date.strftime("%A, %b %d") %>&nbsp;until&nbsp;<%= booking.end_date.strftime("%A, %b %d") %></p>
        <%= link_to "Delete", booking_path(booking), method: :delete, data: {
        confirm: "Are you sure you want to delete this booking? Woof!" }, class: "btn btn-primary"  %>
      </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    Follow us
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <br>

  <div class="footer-copyright" id="text-footer">
    Made with <i class="fas fa-heart"></i>&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;All rights reserved by DoggyBeWithMe
    <%= image_tag 'bone.png', class: "avatar dropdown-toggle", id: "navbarDropdown" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Logo_Dog.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <%= link_to "Discover", dogs_path, class: 'nav-link'  %>
          </li>
        <% if current_user.present? %>
          <li class="nav-item active">
            <%= link_to "Account", profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Add Dog", new_dog_path, class: 'nav-link'  %>
          </li>
          <li class="nav-item dropdown">
          <li class="nav-item active">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Register",  new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <%= image_tag 'bone.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </ul>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>